/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsPanelBakeRouteImport } from './routes/accounts-panel-bake'
import { Route as ArchHeroRouteImport } from './routes/arch-hero'
import { Route as GlobeHorizonRouteImport } from './routes/globe-horizon'
import { Route as Hero3dRouteImport } from './routes/hero-3d'
import { Route as HeroAccountsRouteImport } from './routes/hero-accounts'
import { Route as HeroDepthRouteImport } from './routes/hero-depth'
import { Route as HeroProjectionRouteImport } from './routes/hero-projection'
import { Route as HeroStudioRouteImport } from './routes/hero-studio'
import { Route as MagneticStackRouteImport } from './routes/magnetic-stack'
import { Route as PanelBakeRouteImport } from './routes/panel-bake'
import { Route as ProjectedHeroRouteImport } from './routes/projected-hero'
import { Route as ProjectionLabRouteImport } from './routes/projection-lab'
import { Route as SectionOptionsRouteImport } from './routes/section-options'
import { Route as SectionStackRouteImport } from './routes/section-stack'
import { Route as Version5RouteImport } from './routes/version-5'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsPanelBakeRoute = AccountsPanelBakeRouteImport.update({
  id: '/accounts-panel-bake',
  path: '/accounts-panel-bake',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchHeroRoute = ArchHeroRouteImport.update({
  id: '/arch-hero',
  path: '/arch-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeHorizonRoute = GlobeHorizonRouteImport.update({
  id: '/globe-horizon',
  path: '/globe-horizon',
  getParentRoute: () => rootRouteImport,
} as any)
const Hero3dRoute = Hero3dRouteImport.update({
  id: '/hero-3d',
  path: '/hero-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroAccountsRoute = HeroAccountsRouteImport.update({
  id: '/hero-accounts',
  path: '/hero-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroDepthRoute = HeroDepthRouteImport.update({
  id: '/hero-depth',
  path: '/hero-depth',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroProjectionRoute = HeroProjectionRouteImport.update({
  id: '/hero-projection',
  path: '/hero-projection',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroStudioRoute = HeroStudioRouteImport.update({
  id: '/hero-studio',
  path: '/hero-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MagneticStackRoute = MagneticStackRouteImport.update({
  id: '/magnetic-stack',
  path: '/magnetic-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelBakeRoute = PanelBakeRouteImport.update({
  id: '/panel-bake',
  path: '/panel-bake',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectedHeroRoute = ProjectedHeroRouteImport.update({
  id: '/projected-hero',
  path: '/projected-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionLabRoute = ProjectionLabRouteImport.update({
  id: '/projection-lab',
  path: '/projection-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionOptionsRoute = SectionOptionsRouteImport.update({
  id: '/section-options',
  path: '/section-options',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionStackRoute = SectionStackRouteImport.update({
  id: '/section-stack',
  path: '/section-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const Version5Route = Version5RouteImport.update({
  id: '/version-5',
  path: '/version-5',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts-panel-bake': typeof AccountsPanelBakeRoute
  '/arch-hero': typeof ArchHeroRoute
  '/globe-horizon': typeof GlobeHorizonRoute
  '/hero-3d': typeof Hero3dRoute
  '/hero-accounts': typeof HeroAccountsRoute
  '/hero-depth': typeof HeroDepthRoute
  '/hero-projection': typeof HeroProjectionRoute
  '/hero-studio': typeof HeroStudioRoute
  '/magnetic-stack': typeof MagneticStackRoute
  '/panel-bake': typeof PanelBakeRoute
  '/projected-hero': typeof ProjectedHeroRoute
  '/projection-lab': typeof ProjectionLabRoute
  '/section-options': typeof SectionOptionsRoute
  '/section-stack': typeof SectionStackRoute
  '/version-5': typeof Version5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts-panel-bake': typeof AccountsPanelBakeRoute
  '/arch-hero': typeof ArchHeroRoute
  '/globe-horizon': typeof GlobeHorizonRoute
  '/hero-3d': typeof Hero3dRoute
  '/hero-accounts': typeof HeroAccountsRoute
  '/hero-depth': typeof HeroDepthRoute
  '/hero-projection': typeof HeroProjectionRoute
  '/hero-studio': typeof HeroStudioRoute
  '/magnetic-stack': typeof MagneticStackRoute
  '/panel-bake': typeof PanelBakeRoute
  '/projected-hero': typeof ProjectedHeroRoute
  '/projection-lab': typeof ProjectionLabRoute
  '/section-options': typeof SectionOptionsRoute
  '/section-stack': typeof SectionStackRoute
  '/version-5': typeof Version5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts-panel-bake': typeof AccountsPanelBakeRoute
  '/arch-hero': typeof ArchHeroRoute
  '/globe-horizon': typeof GlobeHorizonRoute
  '/hero-3d': typeof Hero3dRoute
  '/hero-accounts': typeof HeroAccountsRoute
  '/hero-depth': typeof HeroDepthRoute
  '/hero-projection': typeof HeroProjectionRoute
  '/hero-studio': typeof HeroStudioRoute
  '/magnetic-stack': typeof MagneticStackRoute
  '/panel-bake': typeof PanelBakeRoute
  '/projected-hero': typeof ProjectedHeroRoute
  '/projection-lab': typeof ProjectionLabRoute
  '/section-options': typeof SectionOptionsRoute
  '/section-stack': typeof SectionStackRoute
  '/version-5': typeof Version5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts-panel-bake'
    | '/arch-hero'
    | '/globe-horizon'
    | '/hero-3d'
    | '/hero-accounts'
    | '/hero-depth'
    | '/hero-projection'
    | '/hero-studio'
    | '/magnetic-stack'
    | '/panel-bake'
    | '/projected-hero'
    | '/projection-lab'
    | '/section-options'
    | '/section-stack'
    | '/version-5'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts-panel-bake'
    | '/arch-hero'
    | '/globe-horizon'
    | '/hero-3d'
    | '/hero-accounts'
    | '/hero-depth'
    | '/hero-projection'
    | '/hero-studio'
    | '/magnetic-stack'
    | '/panel-bake'
    | '/projected-hero'
    | '/projection-lab'
    | '/section-options'
    | '/section-stack'
    | '/version-5'
  id:
    | '__root__'
    | '/'
    | '/accounts-panel-bake'
    | '/arch-hero'
    | '/globe-horizon'
    | '/hero-3d'
    | '/hero-accounts'
    | '/hero-depth'
    | '/hero-projection'
    | '/hero-studio'
    | '/magnetic-stack'
    | '/panel-bake'
    | '/projected-hero'
    | '/projection-lab'
    | '/section-options'
    | '/section-stack'
    | '/version-5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsPanelBakeRoute: typeof AccountsPanelBakeRoute
  ArchHeroRoute: typeof ArchHeroRoute
  GlobeHorizonRoute: typeof GlobeHorizonRoute
  Hero3dRoute: typeof Hero3dRoute
  HeroAccountsRoute: typeof HeroAccountsRoute
  HeroDepthRoute: typeof HeroDepthRoute
  HeroProjectionRoute: typeof HeroProjectionRoute
  HeroStudioRoute: typeof HeroStudioRoute
  MagneticStackRoute: typeof MagneticStackRoute
  PanelBakeRoute: typeof PanelBakeRoute
  ProjectedHeroRoute: typeof ProjectedHeroRoute
  ProjectionLabRoute: typeof ProjectionLabRoute
  SectionOptionsRoute: typeof SectionOptionsRoute
  SectionStackRoute: typeof SectionStackRoute
  Version5Route: typeof Version5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-panel-bake': {
      id: '/accounts-panel-bake'
      path: '/accounts-panel-bake'
      fullPath: '/accounts-panel-bake'
      preLoaderRoute: typeof AccountsPanelBakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arch-hero': {
      id: '/arch-hero'
      path: '/arch-hero'
      fullPath: '/arch-hero'
      preLoaderRoute: typeof ArchHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe-horizon': {
      id: '/globe-horizon'
      path: '/globe-horizon'
      fullPath: '/globe-horizon'
      preLoaderRoute: typeof GlobeHorizonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-3d': {
      id: '/hero-3d'
      path: '/hero-3d'
      fullPath: '/hero-3d'
      preLoaderRoute: typeof Hero3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-accounts': {
      id: '/hero-accounts'
      path: '/hero-accounts'
      fullPath: '/hero-accounts'
      preLoaderRoute: typeof HeroAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-depth': {
      id: '/hero-depth'
      path: '/hero-depth'
      fullPath: '/hero-depth'
      preLoaderRoute: typeof HeroDepthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-projection': {
      id: '/hero-projection'
      path: '/hero-projection'
      fullPath: '/hero-projection'
      preLoaderRoute: typeof HeroProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-studio': {
      id: '/hero-studio'
      path: '/hero-studio'
      fullPath: '/hero-studio'
      preLoaderRoute: typeof HeroStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magnetic-stack': {
      id: '/magnetic-stack'
      path: '/magnetic-stack'
      fullPath: '/magnetic-stack'
      preLoaderRoute: typeof MagneticStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-bake': {
      id: '/panel-bake'
      path: '/panel-bake'
      fullPath: '/panel-bake'
      preLoaderRoute: typeof PanelBakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projected-hero': {
      id: '/projected-hero'
      path: '/projected-hero'
      fullPath: '/projected-hero'
      preLoaderRoute: typeof ProjectedHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection-lab': {
      id: '/projection-lab'
      path: '/projection-lab'
      fullPath: '/projection-lab'
      preLoaderRoute: typeof ProjectionLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section-options': {
      id: '/section-options'
      path: '/section-options'
      fullPath: '/section-options'
      preLoaderRoute: typeof SectionOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section-stack': {
      id: '/section-stack'
      path: '/section-stack'
      fullPath: '/section-stack'
      preLoaderRoute: typeof SectionStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version-5': {
      id: '/version-5'
      path: '/version-5'
      fullPath: '/version-5'
      preLoaderRoute: typeof Version5RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsPanelBakeRoute: AccountsPanelBakeRoute,
  ArchHeroRoute: ArchHeroRoute,
  GlobeHorizonRoute: GlobeHorizonRoute,
  Hero3dRoute: Hero3dRoute,
  HeroAccountsRoute: HeroAccountsRoute,
  HeroDepthRoute: HeroDepthRoute,
  HeroProjectionRoute: HeroProjectionRoute,
  HeroStudioRoute: HeroStudioRoute,
  MagneticStackRoute: MagneticStackRoute,
  PanelBakeRoute: PanelBakeRoute,
  ProjectedHeroRoute: ProjectedHeroRoute,
  ProjectionLabRoute: ProjectionLabRoute,
  SectionOptionsRoute: SectionOptionsRoute,
  SectionStackRoute: SectionStackRoute,
  Version5Route: Version5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
