/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchHeroRouteImport } from './routes/arch-hero'
import { Route as Hero3dRouteImport } from './routes/hero-3d'
import { Route as HeroDepthRouteImport } from './routes/hero-depth'
import { Route as HeroProjectionRouteImport } from './routes/hero-projection'
import { Route as HeroStudioRouteImport } from './routes/hero-studio'
import { Route as MagneticStackRouteImport } from './routes/magnetic-stack'
import { Route as PanelBakeRouteImport } from './routes/panel-bake'
import { Route as ProjectedHeroRouteImport } from './routes/projected-hero'
import { Route as ProjectionLabRouteImport } from './routes/projection-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchHeroRoute = ArchHeroRouteImport.update({
  id: '/arch-hero',
  path: '/arch-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const Hero3dRoute = Hero3dRouteImport.update({
  id: '/hero-3d',
  path: '/hero-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroDepthRoute = HeroDepthRouteImport.update({
  id: '/hero-depth',
  path: '/hero-depth',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroProjectionRoute = HeroProjectionRouteImport.update({
  id: '/hero-projection',
  path: '/hero-projection',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroStudioRoute = HeroStudioRouteImport.update({
  id: '/hero-studio',
  path: '/hero-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MagneticStackRoute = MagneticStackRouteImport.update({
  id: '/magnetic-stack',
  path: '/magnetic-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelBakeRoute = PanelBakeRouteImport.update({
  id: '/panel-bake',
  path: '/panel-bake',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectedHeroRoute = ProjectedHeroRouteImport.update({
  id: '/projected-hero',
  path: '/projected-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionLabRoute = ProjectionLabRouteImport.update({
  id: '/projection-lab',
  path: '/projection-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arch-hero': typeof ArchHeroRoute
  '/hero-3d': typeof Hero3dRoute
  '/hero-depth': typeof HeroDepthRoute
  '/hero-projection': typeof HeroProjectionRoute
  '/hero-studio': typeof HeroStudioRoute
  '/magnetic-stack': typeof MagneticStackRoute
  '/panel-bake': typeof PanelBakeRoute
  '/projected-hero': typeof ProjectedHeroRoute
  '/projection-lab': typeof ProjectionLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arch-hero': typeof ArchHeroRoute
  '/hero-3d': typeof Hero3dRoute
  '/hero-depth': typeof HeroDepthRoute
  '/hero-projection': typeof HeroProjectionRoute
  '/hero-studio': typeof HeroStudioRoute
  '/magnetic-stack': typeof MagneticStackRoute
  '/panel-bake': typeof PanelBakeRoute
  '/projected-hero': typeof ProjectedHeroRoute
  '/projection-lab': typeof ProjectionLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arch-hero': typeof ArchHeroRoute
  '/hero-3d': typeof Hero3dRoute
  '/hero-depth': typeof HeroDepthRoute
  '/hero-projection': typeof HeroProjectionRoute
  '/hero-studio': typeof HeroStudioRoute
  '/magnetic-stack': typeof MagneticStackRoute
  '/panel-bake': typeof PanelBakeRoute
  '/projected-hero': typeof ProjectedHeroRoute
  '/projection-lab': typeof ProjectionLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arch-hero'
    | '/hero-3d'
    | '/hero-depth'
    | '/hero-projection'
    | '/hero-studio'
    | '/magnetic-stack'
    | '/panel-bake'
    | '/projected-hero'
    | '/projection-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arch-hero'
    | '/hero-3d'
    | '/hero-depth'
    | '/hero-projection'
    | '/hero-studio'
    | '/magnetic-stack'
    | '/panel-bake'
    | '/projected-hero'
    | '/projection-lab'
  id:
    | '__root__'
    | '/'
    | '/arch-hero'
    | '/hero-3d'
    | '/hero-depth'
    | '/hero-projection'
    | '/hero-studio'
    | '/magnetic-stack'
    | '/panel-bake'
    | '/projected-hero'
    | '/projection-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchHeroRoute: typeof ArchHeroRoute
  Hero3dRoute: typeof Hero3dRoute
  HeroDepthRoute: typeof HeroDepthRoute
  HeroProjectionRoute: typeof HeroProjectionRoute
  HeroStudioRoute: typeof HeroStudioRoute
  MagneticStackRoute: typeof MagneticStackRoute
  PanelBakeRoute: typeof PanelBakeRoute
  ProjectedHeroRoute: typeof ProjectedHeroRoute
  ProjectionLabRoute: typeof ProjectionLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arch-hero': {
      id: '/arch-hero'
      path: '/arch-hero'
      fullPath: '/arch-hero'
      preLoaderRoute: typeof ArchHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-3d': {
      id: '/hero-3d'
      path: '/hero-3d'
      fullPath: '/hero-3d'
      preLoaderRoute: typeof Hero3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-depth': {
      id: '/hero-depth'
      path: '/hero-depth'
      fullPath: '/hero-depth'
      preLoaderRoute: typeof HeroDepthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-projection': {
      id: '/hero-projection'
      path: '/hero-projection'
      fullPath: '/hero-projection'
      preLoaderRoute: typeof HeroProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-studio': {
      id: '/hero-studio'
      path: '/hero-studio'
      fullPath: '/hero-studio'
      preLoaderRoute: typeof HeroStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magnetic-stack': {
      id: '/magnetic-stack'
      path: '/magnetic-stack'
      fullPath: '/magnetic-stack'
      preLoaderRoute: typeof MagneticStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-bake': {
      id: '/panel-bake'
      path: '/panel-bake'
      fullPath: '/panel-bake'
      preLoaderRoute: typeof PanelBakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projected-hero': {
      id: '/projected-hero'
      path: '/projected-hero'
      fullPath: '/projected-hero'
      preLoaderRoute: typeof ProjectedHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection-lab': {
      id: '/projection-lab'
      path: '/projection-lab'
      fullPath: '/projection-lab'
      preLoaderRoute: typeof ProjectionLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchHeroRoute: ArchHeroRoute,
  Hero3dRoute: Hero3dRoute,
  HeroDepthRoute: HeroDepthRoute,
  HeroProjectionRoute: HeroProjectionRoute,
  HeroStudioRoute: HeroStudioRoute,
  MagneticStackRoute: MagneticStackRoute,
  PanelBakeRoute: PanelBakeRoute,
  ProjectedHeroRoute: ProjectedHeroRoute,
  ProjectionLabRoute: ProjectionLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
